apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-configmap
data:
  start.sh: |
    #!/bin/sh
    export BASIC_AUTH_PASSWORD=$(cat /mnt/secrets-store/test)
    java -jar /app.jar