apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        group: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
        - name: aws-auth
      serviceAccountName: spring-boot
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            limits:
              cpu: 400m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 300Mi
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
            - name: config-volume
              mountPath: /script/start.sh
              subPath: start.sh

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
        - name: config-volume
          configMap:
            name: {{ .Values.app.name }}-configmap
            defaultMode: 0755
      restartPolicy: Always