apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.name }}-memory-hpa
  namespace: ns-app
spec:
  maxReplicas: 6
  minReplicas: {{ .Values.replicaCount }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageValue: {{ .Values.memory.target }}