apiVersion: v1
kind: Service
metadata:
  name: spring-boot
spec:
  type: ClusterIP
  selector:
    app: spring-boot
  ports:
    - name: service
      protocol: TCP
      port: 8080
      targetPort: 8080