replicaCount: 1
app:
  name: "spring-boot"
cpu:
  target: "390m"
  #This is 85% of the cpu limit set.
memory:
  target: "480Mi"
  #This is 85% of the memory limit set.
pv:
  name: ""
pvc:
  name: "spring-boot-pvc"
  storage: "5Gi"

image:
  repository: "716107848499.dkr.ecr.eu-west-1.amazonaws.com/spring-boot"
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
imagePullSecrets:
  name: aws-auth

nodeSelector: {}

tolerations: []

affinity: {}
